### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [digital-botanical-gardens-initiative/gpkg_creator#1]
# Problem

Please update Plugin homepage from https://www.dbgi.org/dendron-dbgi/ to the plugin repository. Ideally, it should refer to a page mentioning the plugin

**Comment by edouardbruelhart** [comment]
Ok sorry,

I changed the Plugin home page to: https://www.dbgi.org/dendron-dbgi/notes/1u37mlza55e6dgksabcv7qn/

Is it good like that?
