### ISSUE TITLE
Tracking uncolleced plant by adding an observation without collecting the plant 

### ISSUE THREAD

**Issue by HeloiseCoen** [digital-botanical-gardens-initiative/gpkg_creator#6]
We need to collect the plants to add an observation to the application. It would be good to be able to trace the plants we haven't been able to collect by adding an observation without scanning the DBGI label, putting in a photo and a location to find the plant. Maybe with another special layer.  That way we can keep track of uncollected plants and come back to them later.

**Comment by edouardbruelhart** [comment]
This option will be available in the next version of the plugin
